version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 2.2
    build:
        commands:
            - dotnet build -c Release ./SearchApi/SearchApi.csproj
            - dotnet test -c Release ./SearchApiTests/SearchApiTests.csproj
